rules:
  type-enum: [2, "always", ["feat", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "chore", "revert", "bump"]]
  type-case: [2, "always", "lower-case"]
  type-empty: [0, "never"]
  scope-case: [2, "always", "lower-case"]
  scope-empty: [0, "never"]
  subject-case: [0, "never", []]
  subject-empty: [0, "never"]
  subject-full-stop: [0, "never"]
  header-max-length: [2, "always", 72]
